name: prelude-prime
synopsis: My custom prelude, plus additional utilities
version: 0.1.0.0
author: Lloyd Cunningham
maintainer: lloyd.cunningham@me.com
copyright: 2018 Lloyd Cunningham
category: Prelude

flags:
  ignore-asserts:
    description: Causes the assert functions to become identity functions.
    default: false
    manual: true

dependencies:
  - base >= 4.10 && < 5
  - deepseq
  - exceptions
  - unliftio-core

default-extensions:
  - NoImplicitPrelude

ghc-options:
  - -Wall
  - -Werror
  - -fwarn-tabs

when:
  condition: flag(ignore-asserts)
  then:
    cpp-options: -DASSERT=0
  else:
    cpp-options: -DASSERT=1

library:
  source-dirs: src
  exposed-modules:
    - PreludePrime
    - PreludePrime.Exception
    - PreludePrime.Numeric
  other-modules: []
